### ISSUE TITLE
Configurar Rubocop

### ISSUE THREAD

**Issue by marcuxyz** [negrosdev/negros.dev#84]
## User Story

**Eu**, como desenvolver
**Quero**, quê o Github CI comece a executar em suas esteira o rubocop
**Para que**, faça uma analise na qualidade de escrita de código

## Objetivo

Analisar qualidade de código. 

## Critérios de aceite

- Configurar o arquivo `.rubocop.yml` com regras do **rubocop**.
- Será necessário instalar o `rubocop-rails`.
- Configurar um novo arquivo dentro de `.github/workflows/` para rodar o rubocop
- Executar o comando `rubocop -a` para corrigir os arquivos que estão fora da regra.

## Template

```yaml
require: rubocop-rails

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.2.0
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'app/admin/auth/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Metrics/BlockLength:
  Max: 120


```
